name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extract version from tags
        id: get_version
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          # Extract the numeric part and increment it
          if [[ $latest_tag =~ ^0\.0\.[0-9]+$ ]]; then
            latest_version=${latest_tag#0.0.}
            new_version=$((latest_version + 1))
            new_tag="0.0.${new_version}"
          else
            new_tag="0.0.1"
          fi
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            akki2208/aws-acm-operator:latest
            akki2208/aws-acm-operator:${{ env.new_tag }}

      - name: Log out from Docker Hub
        run: docker logout
